### PR TITLE
Golly:  The 2.6-mac109 download is no longer available.

### LINKED ISSUE #10155: Golly doesn't install
```
lahwran@lahwran:~$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
Already up-to-date.
Error: brew-cask 0.53.3 already installed
lahwran@lahwran:~$ brew cask install golly
==> Caveats
Cask golly installs files under "/usr/local".  The presence of such
files can cause warnings when running "brew doctor", which is considered
to be a bug in homebrew-cask.

==> Downloading http://downloads.sourceforge.net/project/golly/golly/golly-2.6/golly-2.6-mac109.zip
Already downloaded: /Library/Caches/Homebrew/golly-2.6.zip
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/golly/2.6/golly-2.6-mac109/Golly.app'
lahwran@lahwran:~$
```

### PR DESCRIPTION
**Pull request by pthariensflame**
Closes #10155.

This pull request makes the cask use the `2.7b3` download instead.

### CODE REVIEW

File: Casks/golly.rb [hunk 1]
```diff
@@ -1,7 +1,7 @@
 cask :v1 => 'golly' do
-  version '2.6'
-
   if MacOS.release <= :mountain_lion
+  	version '2.6'
+
```
Comment (vitorgalvao) [inline Casks/golly.rb]: This line needs to be removed.

File: Casks/golly.rb [hunk 2]
```diff
@@ -9,7 +9,9 @@
     app "golly-#{version}-mac106/Golly.app"
     binary "golly-#{version}-mac106/bgolly"
   else
-    sha256 '8e2e7ffd22dd046a701b6db13a1c36939eced46078c85eeccf709072183fb71c'
+  	version '2.7b3'
+
```
Comment (vitorgalvao) [inline Casks/golly.rb]: This line needs to be removed.

File: Casks/golly.rb [hunk 3]
```diff
@@ -1,7 +1,7 @@
 cask :v1 => 'golly' do
-  version '2.6'
-
   if MacOS.release <= :mountain_lion
+  	version '2.6'
```
Comment (vitorgalvao) [inline Casks/golly.rb]: This line has too much indentation.

File: Casks/golly.rb [hunk 4]
```diff
@@ -9,7 +9,9 @@
     app "golly-#{version}-mac106/Golly.app"
     binary "golly-#{version}-mac106/bgolly"
   else
-    sha256 '8e2e7ffd22dd046a701b6db13a1c36939eced46078c85eeccf709072183fb71c'
+  	version '2.7b3'
```
Comment (vitorgalvao) [inline Casks/golly.rb]: This line has too much indentation.

**Comment by pthariensflame** [comment]
@vitorgalvao How about now?

**Comment by vitorgalvao** [comment]
The empty lines you added are still there. Those should be removed.

**Comment by pthariensflame** [comment]
Oh, I see!  I thought you were just talking about the trailing whitespace.

**Comment by vitorgalvao** [comment]
Looks good, could you please [squash your commits](http://davidwalsh.name/squash-commits-git)?

**Comment by pthariensflame** [comment]
@vitorgalvao Done!

**Comment by vitorgalvao** [comment]
Thank you. Looks great.
