### PR TITLE
mono-mdk: Cask is updated in-place, use sha256 :no_check

### LINKED ISSUE #8610: brew cask install mono-mdk gives SHA2 mismatch
When attempting to install mono-mdk, I get

```
➜  ~  brew cask install mono-mdk
==> Downloading http://download.mono-project.com/archive/3.10.0/macos-10-x86/MonoFramework-MDK-3.10.0.macos10.xamarin.x86.pkg
######################################################################## 100.0%
==> Note: running "brew update" may fix checksum errors
Error: SHA2 mismatch
Expected: e71b558c2b7857c124ccbb5e73bc622733e1cd5da494a7b5d9d14a90f555c1b8
Actual: dccf2478906689221788d6c1799acb05ee41502c4316339bccd8727e092fd868
Archive: /Library/Caches/Homebrew/mono-mdk-3.10.0.pkg
To retry an incomplete download, remove the file above.
```

### PR DESCRIPTION
**Pull request by jawshooah**
Closes #8610.

### CODE REVIEW

File: Casks/mono-mdk.rb [hunk 1]
```diff
@@ -1,6 +1,6 @@
 cask :v1 => 'mono-mdk' do
   version '3.10.0'
-  sha256 'e71b558c2b7857c124ccbb5e73bc622733e1cd5da494a7b5d9d14a90f555c1b8'
+  sha256 :no_check
```
Comment (vitorgalvao) [inline Casks/mono-mdk.rb]: Please add a `# required as upstream package is updated in-place` comment in front (as in [`adobe-air`](https://github.com/caskroom/homebrew-cask/blob/b86132f5732bc9f0919aaa56cb519bf57ad236a6/Casks/adobe-air.rb). This is needed so (mainly) first-time contributors don’t use it when there isn’t a valid reason (happens with some frequency).

**Comment by jawshooah** [comment]
@vitorgalvao Good call, done.
