### PR TITLE
docker: add caveats

### LINKED ISSUE #146078: Can't install both docker CLI and Docker app
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

I am unable to `brew` both `docker` and `--cask docker` to have both the CLI tool and the Docker app. Normally, I'd `open -a docker` to get the docker daemon running, and then use `docker` normally. I am unable to do that with `brew install --cask docker` due to conflicting files.

```
~$ brew install --cask docker
==> Caveats
If your CLI tools were symlinked to $HOME/.docker/bin your path should be modified to include:

  $HOME/.docker/bin

==> Downloading https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
######################################################################### 100.0%
==> Installing Cask docker
==> Moving App 'Docker.app' to '/Applications/Docker.app'
==> Backing App 'Docker.app' up to '/usr/local/Caskroom/docker/4.19.0,106363/Doc
==> Removing App '/Applications/Docker.app'
==> Purging files for version 4.19.0,106363 of Cask docker
Error: It seems there is already a Binary at '/usr/local/share/zsh/site-functions/_docker'.
~$ brew install --cask docker --force
==> Downloading https://formulae.brew.sh/api/cask.jws.json
##O#- #                                                                        
==> Caveats
If your CLI tools were symlinked to $HOME/.docker/bin your path should be modified to include:

  $HOME/.docker/bin

==> Downloading https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
Already downloaded: /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> Installing Cask docker
==> Moving App 'Docker.app' to '/Applications/Docker.app'
==> Backing App 'Docker.app' up to '/usr/local/Caskroom/docker/4.19.0,106363/Doc
==> Removing App '/Applications/Docker.app'
==> Purging files for version 4.19.0,106363 of Cask docker
Error: It seems there is already a Binary at '/usr/local/share/zsh/site-functions/_docker'.
```

See Homebrew/homebrew-core#129609 for previous attempts.

Note: installing Docker from https://www.docker.com/ "just works":

```
~$ docker run -it alpine
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
~$ open -a docker
~$ docker run -it alpine
/ # uname -a
Linux 6bd2242fcb25 5.15.49-linuxkit #1 SMP Tue Sep 13 07:51:46 UTC 2022 x86_64 Linux
/ # 
```

Here is the full output of all the commands I tried since starting this issue:

```
Last login: Fri Apr 28 03:49:28 on ttys001

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
~$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
Warning: This script will remove:
/Users/osos/Library/Caches/Homebrew/
/usr/local/Caskroom/
/usr/local/Cellar/
/usr/local/bin/brew -> /usr/local/bin/brew
Are you sure you want to uninstall Homebrew? This will remove your installed packages! [y/N] y
==> Removing Homebrew installation...
Warning: Failed to delete /usr/local/Caskroom
rm: /usr/local/Caskroom: Permission denied
Warning: Failed to delete /usr/local/Cellar
rm: /usr/local/Cellar: Permission denied
==> Removing empty directories...
Password:
==> /usr/bin/sudo /usr/bin/find /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/var /usr/local/Caskroom /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks -name .DS_Store -delete
==> /usr/bin/sudo /usr/bin/find /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share /usr/local/var /usr/local/Caskroom /usr/local/Cellar /usr/local/Homebrew /usr/local/Frameworks -depth -type d -empty -exec rmdir {} ;
==> Homebrew uninstalled!
The following possible Homebrew files were not deleted:
/usr/local/Frameworks/
/usr/local/Homebrew/
/usr/local/bin/
/usr/local/etc/
/usr/local/go/
/usr/local/include/
/usr/local/lib/
/usr/local/mysql -> /usr/local/mysql
/usr/local/mysql-8.0.32-macos13-x86_64/
/usr/local/opt/
/usr/local/sbin/
/usr/local/share/
/usr/local/var/
You may wish to remove them yourself.

~$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password)...
Password:
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following new directories will be created:
/usr/local/Cellar
/usr/local/Caskroom

Press RETURN/ENTER to continue or any other key to abort:
==> /usr/bin/sudo /bin/mkdir -p /usr/local/Cellar /usr/local/Caskroom
==> /usr/bin/sudo /bin/chmod ug=rwx /usr/local/Cellar /usr/local/Caskroom
==> /usr/bin/sudo /usr/sbin/chown osos /usr/local/Cellar /usr/local/Caskroom
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/Cellar /usr/local/Caskroom
==> /usr/bin/sudo /usr/sbin/chown -R osos:admin /usr/local/Homebrew
==> /usr/bin/sudo /bin/mkdir -p /Users/osos/Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Users/osos/Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown -R osos /Users/osos/Library/Caches/Homebrew
==> Downloading and installing Homebrew...
HEAD is now at e191b827c Merge pull request #15257 from Bo98/download-refactor
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics data has been sent yet (nor will any be during this install run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Next steps:
- Run brew help to get started
- Further documentation:
    https://docs.brew.sh

~$ docker run alpine
-bash: docker: command not found
~$ file '/usr/local/share/zsh/site-functions/_docker'
/usr/local/share/zsh/site-functions/_docker: cannot open `/usr/local/share/zsh/site-functions/_docker' (No such file or directory)
~$ brew install docker
Warning: Treating docker as a formula. For the cask, use homebrew/cask/docker
==> Fetching docker
==> Downloading https://ghcr.io/v2/homebrew/core/docker/manifests/23.0.5
######################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/docker/blobs/sha256:aa59d361b28
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################### 100.0%
==> Pouring docker--23.0.5.monterey.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/docker/23.0.5: 12 files, 32.5MB
==> Running `brew cleanup docker`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
~$ file '/usr/local/share/zsh/site-functions/_docker'
/usr/local/share/zsh/site-functions/_docker: ASCII text
~$ docker run alpine
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
~$ open -a docker
Unable to find application named 'docker'
~$ brew install --cask docker
==> Caveats
If your CLI tools were symlinked to $HOME/.docker/bin your path should be modified to include:

  $HOME/.docker/bin

==> Downloading https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
######################################################################### 100.0%
==> Installing Cask docker
==> Moving App 'Docker.app' to '/Applications/Docker.app'
==> Backing App 'Docker.app' up to '/usr/local/Caskroom/docker/4.19.0,106363/Doc
==> Removing App '/Applications/Docker.app'
==> Purging files for version 4.19.0,106363 of Cask docker
Error: It seems there is already a Binary at '/usr/local/share/zsh/site-functions/_docker'.
~$ brew install --cask docker --force
==> Downloading https://formulae.brew.sh/api/cask.jws.json
##O#- #                                                                        
==> Caveats
If your CLI tools were symlinked to $HOME/.docker/bin your path should be modified to include:

  $HOME/.docker/bin

==> Downloading https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
Already downloaded: /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> Installing Cask docker
==> Moving App 'Docker.app' to '/Applications/Docker.app'
==> Backing App 'Docker.app' up to '/usr/local/Caskroom/docker/4.19.0,106363/Doc
==> Removing App '/Applications/Docker.app'
==> Purging files for version 4.19.0,106363 of Cask docker
Error: It seems there is already a Binary at '/usr/local/share/zsh/site-functions/_docker'.
~$ update-reset && brew update
-bash: update-reset: command not found
~$ brew update-reset && brew update
==> Fetching /usr/local/Homebrew...

==> Resetting /usr/local/Homebrew...
branch 'master' set up to track 'origin/master'.
Switched to and reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask...
Updating files: 100% (4231/4231), done.
branch 'master' set up to track 'origin/master'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/null-dev/homebrew-firefox-profile-switcher...

==> Resetting /usr/local/Homebrew/Library/Taps/null-dev/homebrew-firefox-profile-switcher...
branch 'master' set up to track 'origin/master'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

Already up-to-date.
~$ brew install --cask docker --force
==> Caveats
If your CLI tools were symlinked to $HOME/.docker/bin your path should be modified to include:

  $HOME/.docker/bin

==> Downloading https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
Already downloaded: /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> Installing Cask docker
==> Moving App 'Docker.app' to '/Applications/Docker.app'
==> Backing App 'Docker.app' up to '/usr/local/Caskroom/docker/4.19.0,106363/Doc
==> Removing App '/Applications/Docker.app'
==> Purging files for version 4.19.0,106363 of Cask docker
Error: It seems there is already a Binary at '/usr/local/share/zsh/site-functions/_docker'.
~$ brew install --cask docker --verbose --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading docker
==> Cask::Installer#install
==> Printing caveats
==> Caveats
If your CLI tools were symlinked to $HOME/.docker/bin your path should be modified to include:

  $HOME/.docker/bin

==> Cask::Installer#fetch
==> Downloading https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.15-97-ge191b82\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6.5\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.15-97-ge191b82\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6.5\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
Already downloaded: /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target x86_64-apple-macosx12 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg is quarantined
==> Verifying checksum for 'a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg'
/usr/bin/env tar --list --file /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env hdiutil imageinfo -format /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> Installing Cask docker
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20230428-68443-leotcq /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env find . -print0
/usr/bin/env mkbom -s -i /private/tmp/20230428-68443-kyiduu.list -- /private/tmp/20230428-68443-mhjtgl.bom
/usr/bin/env ditto --bom /private/tmp/20230428-68443-mhjtgl.bom -- /private/tmp/d20230428-68443-leotcq/dmg.lkMURl /private/tmp/d20230428-68443-txbqqu
/usr/bin/env diskutil info -plist /private/tmp/d20230428-68443-leotcq/dmg.lkMURl
/usr/bin/env diskutil eject /private/tmp/d20230428-68443-leotcq/dmg.lkMURl
/usr/bin/env cp -pR /private/tmp/d20230428-68443-txbqqu/Docker.app/. /usr/local/Caskroom/docker/4.19.0,106363/Docker.app
==> Verifying Gatekeeper status of /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg is quarantined
==> Propagating quarantine from /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg to /usr/local/Caskroom/docker/4.19.0,106363
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;644b7c01\;Homebrew\\x20Cask\;19CE4232-A908-4B4D-8ECA-0B63323E829A
==> Creating metadata directory: /usr/local/Caskroom/docker/.metadata/4.19.0,106363/20230428080201.781
==> Creating metadata subdirectory: /usr/local/Caskroom/docker/.metadata/4.19.0,106363/20230428080201.781/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::App
==> Moving App 'Docker.app' to '/Applications/Docker.app'
==> Installing artifact of class Cask::Artifact::Binary
==> Reverting installation of artifact of class Cask::Artifact::App
==> Backing App 'Docker.app' up to '/usr/local/Caskroom/docker/4.19.0,106363/Docker.app'
/usr/bin/env /bin/cp -pR /Applications/Docker.app /usr/local/Caskroom/docker/4.19.0,106363/Docker.app
==> Removing App '/Applications/Docker.app'
==> Purging files for version 4.19.0,106363 of Cask docker
Error: It seems there is already a Binary at '/usr/local/share/zsh/site-functions/_docker'.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:62:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/binary.rb:13:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:23:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:235:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:228:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
~$ brew install --cask docker --force --verbose --debug
~$ brew install --cask docker --force --verbose --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading docker
==> Cask::Installer#install
==> Printing caveats
==> Caveats
If your CLI tools were symlinked to $HOME/.docker/bin your path should be modified to include:

  $HOME/.docker/bin

==> Cask::Installer#fetch
==> Downloading https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.15-97-ge191b82\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6.5\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.15-97-ge191b82\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6.5\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
Already downloaded: /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target x86_64-apple-macosx12 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg is quarantined
==> Verifying checksum for 'a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg'
/usr/bin/env tar --list --file /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env hdiutil imageinfo -format /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> Installing Cask docker
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20230428-68678-imjim6 /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env find . -print0
/usr/bin/env mkbom -s -i /private/tmp/20230428-68678-sif5gj.list -- /private/tmp/20230428-68678-1ijiouw.bom
/usr/bin/env ditto --bom /private/tmp/20230428-68678-1ijiouw.bom -- /private/tmp/d20230428-68678-imjim6/dmg.9o6DEr /private/tmp/d20230428-68678-eukr9t
/usr/bin/env diskutil info -plist /private/tmp/d20230428-68678-imjim6/dmg.9o6DEr
/usr/bin/env diskutil eject /private/tmp/d20230428-68678-imjim6/dmg.9o6DEr
/usr/bin/env cp -pR /private/tmp/d20230428-68678-eukr9t/Docker.app/. /usr/local/Caskroom/docker/4.19.0,106363/Docker.app
==> Verifying Gatekeeper status of /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg is quarantined
==> Propagating quarantine from /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg to /usr/local/Caskroom/docker/4.19.0,106363
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;644b7c01\;Homebrew\\x20Cask\;19CE4232-A908-4B4D-8ECA-0B63323E829A
==> Creating metadata directory: /usr/local/Caskroom/docker/.metadata/4.19.0,106363/20230428080339.734
==> Creating metadata subdirectory: /usr/local/Caskroom/docker/.metadata/4.19.0,106363/20230428080339.734/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::App
==> Moving App 'Docker.app' to '/Applications/Docker.app'
==> Installing artifact of class Cask::Artifact::Binary
==> Reverting installation of artifact of class Cask::Artifact::App
==> Backing App 'Docker.app' up to '/usr/local/Caskroom/docker/4.19.0,106363/Docker.app'
/usr/bin/env /bin/cp -pR /Applications/Docker.app /usr/local/Caskroom/docker/4.19.0,106363/Docker.app
==> Removing App '/Applications/Docker.app'
==> Purging files for version 4.19.0,106363 of Cask docker
Error: It seems there is already a Binary at '/usr/local/share/zsh/site-functions/_docker'.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:62:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/binary.rb:13:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:23:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:235:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:228:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
~$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/etc/bash_completion.d/docker-compose
  /usr/local/share/fish/vendor_completions.d/docker-compose.fish
  /usr/local/share/zsh/site-functions/_docker_compose
~$ brew cleanup
Pruned 3 symbolic links from /usr/local
~$ brew doctor
Your system is ready to brew.
~$ brew install --cask docker
==> Caveats
If your CLI tools were symlinked to $HOME/.docker/bin your path should be modified to include:

  $HOME/.docker/bin

==> Downloading https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
Already downloaded: /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> Installing Cask docker
==> Moving App 'Docker.app' to '/Applications/Docker.app'
==> Backing App 'Docker.app' up to '/usr/local/Caskroom/docker/4.19.0,106363/Doc
==> Removing App '/Applications/Docker.app'
==> Purging files for version 4.19.0,106363 of Cask docker
Error: It seems there is already a Binary at '/usr/local/share/zsh/site-functions/_docker'.
~$ brew install --cask docker --verbose --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading docker
==> Cask::Installer#install
==> Printing caveats
==> Caveats
If your CLI tools were symlinked to $HOME/.docker/bin your path should be modified to include:

  $HOME/.docker/bin

==> Cask::Installer#fetch
==> Downloading https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.15-97-ge191b82\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6.5\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.15-97-ge191b82\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6.5\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
Already downloaded: /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target x86_64-apple-macosx12 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg is quarantined
==> Verifying checksum for 'a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg'
/usr/bin/env tar --list --file /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env hdiutil imageinfo -format /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> Installing Cask docker
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20230428-70204-100klfg /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env find . -print0
/usr/bin/env mkbom -s -i /private/tmp/20230428-70204-ru4ozs.list -- /private/tmp/20230428-70204-rxtezc.bom
/usr/bin/env ditto --bom /private/tmp/20230428-70204-rxtezc.bom -- /private/tmp/d20230428-70204-100klfg/dmg.LAmnZi /private/tmp/d20230428-70204-184xtyh
/usr/bin/env diskutil info -plist /private/tmp/d20230428-70204-100klfg/dmg.LAmnZi
/usr/bin/env diskutil eject /private/tmp/d20230428-70204-100klfg/dmg.LAmnZi
/usr/bin/env cp -pR /private/tmp/d20230428-70204-184xtyh/Docker.app/. /usr/local/Caskroom/docker/4.19.0,106363/Docker.app
==> Verifying Gatekeeper status of /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg is quarantined
==> Propagating quarantine from /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg to /usr/local/Caskroom/docker/4.19.0,106363
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;644b7c01\;Homebrew\\x20Cask\;19CE4232-A908-4B4D-8ECA-0B63323E829A
==> Creating metadata directory: /usr/local/Caskroom/docker/.metadata/4.19.0,106363/20230428080708.917
==> Creating metadata subdirectory: /usr/local/Caskroom/docker/.metadata/4.19.0,106363/20230428080708.917/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::App
==> Moving App 'Docker.app' to '/Applications/Docker.app'
==> Installing artifact of class Cask::Artifact::Binary
==> Reverting installation of artifact of class Cask::Artifact::App
==> Backing App 'Docker.app' up to '/usr/local/Caskroom/docker/4.19.0,106363/Docker.app'
/usr/bin/env /bin/cp -pR /Applications/Docker.app /usr/local/Caskroom/docker/4.19.0,106363/Docker.app
==> Removing App '/Applications/Docker.app'
==> Purging files for version 4.19.0,106363 of Cask docker
Error: It seems there is already a Binary at '/usr/local/share/zsh/site-functions/_docker'.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:62:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/binary.rb:13:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:23:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:235:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:228:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
~$ brew install --cask docker --force
==> Downloading https://formulae.brew.sh/api/cask.jws.json
#=#=#                                                                          
==> Caveats
If your CLI tools were symlinked to $HOME/.docker/bin your path should be modified to include:

  $HOME/.docker/bin

==> Downloading https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
Already downloaded: /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> Installing Cask docker
==> Moving App 'Docker.app' to '/Applications/Docker.app'
==> Backing App 'Docker.app' up to '/usr/local/Caskroom/docker/4.19.0,106363/Doc
==> Removing App '/Applications/Docker.app'
==> Purging files for version 4.19.0,106363 of Cask docker
Error: It seems there is already a Binary at '/usr/local/share/zsh/site-functions/_docker'.
~$ brew install --cask docker --force --verbose --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading docker
==> Cask::Installer#install
==> Printing caveats
==> Caveats
If your CLI tools were symlinked to $HOME/.docker/bin your path should be modified to include:

  $HOME/.docker/bin

==> Cask::Installer#fetch
==> Downloading https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.15-97-ge191b82\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6.5\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.15-97-ge191b82\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6.5\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
Already downloaded: /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target x86_64-apple-macosx12 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg is quarantined
==> Verifying checksum for 'a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg'
/usr/bin/env tar --list --file /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env hdiutil imageinfo -format /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> Installing Cask docker
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20230428-70671-orsing /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env find . -print0
/usr/bin/env mkbom -s -i /private/tmp/20230428-70671-1oh1fjw.list -- /private/tmp/20230428-70671-hg5nss.bom
/usr/bin/env ditto --bom /private/tmp/20230428-70671-hg5nss.bom -- /private/tmp/d20230428-70671-orsing/dmg.I3Z1TV /private/tmp/d20230428-70671-1jod9yr
/usr/bin/env diskutil info -plist /private/tmp/d20230428-70671-orsing/dmg.I3Z1TV
/usr/bin/env diskutil eject /private/tmp/d20230428-70671-orsing/dmg.I3Z1TV
/usr/bin/env cp -pR /private/tmp/d20230428-70671-1jod9yr/Docker.app/. /usr/local/Caskroom/docker/4.19.0,106363/Docker.app
==> Verifying Gatekeeper status of /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg is quarantined
==> Propagating quarantine from /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg to /usr/local/Caskroom/docker/4.19.0,106363
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;644b7c01\;Homebrew\\x20Cask\;19CE4232-A908-4B4D-8ECA-0B63323E829A
==> Creating metadata directory: /usr/local/Caskroom/docker/.metadata/4.19.0,106363/20230428081002.180
==> Creating metadata subdirectory: /usr/local/Caskroom/docker/.metadata/4.19.0,106363/20230428081002.180/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::App
==> Moving App 'Docker.app' to '/Applications/Docker.app'
==> Installing artifact of class Cask::Artifact::Binary
==> Reverting installation of artifact of class Cask::Artifact::App
==> Backing App 'Docker.app' up to '/usr/local/Caskroom/docker/4.19.0,106363/Docker.app'
/usr/bin/env /bin/cp -pR /Applications/Docker.app /usr/local/Caskroom/docker/4.19.0,106363/Docker.app
==> Removing App '/Applications/Docker.app'
==> Purging files for version 4.19.0,106363 of Cask docker
Error: It seems there is already a Binary at '/usr/local/share/zsh/site-functions/_docker'.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:62:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/binary.rb:13:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:23:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:235:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:228:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
~$ brew doctor
Your system is ready to brew.
~$ brew config
HOMEBREW_VERSION: 4.0.15-97-ge191b82
ORIGIN: https://github.com/Homebrew/brew
HEAD: e191b827cce991f52be36b0a8fc3daed3ef66143
Last commit: 40 minutes ago
Core tap JSON: 28 Apr 07:59 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 12.6.5-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
~$ brew tap
homebrew/cask
null-dev/firefox-profile-switcher
~$ 
```

### Command that failed

brew install --cask docker

### Output of command with `--verbose --debug`

```shell
~$ brew install --cask docker --verbose --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading docker
==> Cask::Installer#install
==> Printing caveats
==> Caveats
If your CLI tools were symlinked to $HOME/.docker/bin your path should be modified to include:

  $HOME/.docker/bin

==> Cask::Installer#fetch
==> Downloading https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.15-97-ge191b82\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6.5\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.15-97-ge191b82\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.6.5\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
Already downloaded: /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /usr/bin/swift -target x86_64-apple-macosx12 /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg is quarantined
==> Verifying checksum for 'a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg'
/usr/bin/env tar --list --file /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env hdiutil imageinfo -format /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> Installing Cask docker
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20230428-70204-100klfg /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env find . -print0
/usr/bin/env mkbom -s -i /private/tmp/20230428-70204-ru4ozs.list -- /private/tmp/20230428-70204-rxtezc.bom
/usr/bin/env ditto --bom /private/tmp/20230428-70204-rxtezc.bom -- /private/tmp/d20230428-70204-100klfg/dmg.LAmnZi /private/tmp/d20230428-70204-184xtyh
/usr/bin/env diskutil info -plist /private/tmp/d20230428-70204-100klfg/dmg.LAmnZi
/usr/bin/env diskutil eject /private/tmp/d20230428-70204-100klfg/dmg.LAmnZi
/usr/bin/env cp -pR /private/tmp/d20230428-70204-184xtyh/Docker.app/. /usr/local/Caskroom/docker/4.19.0,106363/Docker.app
==> Verifying Gatekeeper status of /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
==> /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg is quarantined
==> Propagating quarantine from /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg to /usr/local/Caskroom/docker/4.19.0,106363
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;644b7c01\;Homebrew\\x20Cask\;19CE4232-A908-4B4D-8ECA-0B63323E829A
==> Creating metadata directory: /usr/local/Caskroom/docker/.metadata/4.19.0,106363/20230428080708.917
==> Creating metadata subdirectory: /usr/local/Caskroom/docker/.metadata/4.19.0,106363/20230428080708.917/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::App
==> Moving App 'Docker.app' to '/Applications/Docker.app'
==> Installing artifact of class Cask::Artifact::Binary
==> Reverting installation of artifact of class Cask::Artifact::App
==> Backing App 'Docker.app' up to '/usr/local/Caskroom/docker/4.19.0,106363/Docker.app'
/usr/bin/env /bin/cp -pR /Applications/Docker.app /usr/local/Caskroom/docker/4.19.0,106363/Docker.app
==> Removing App '/Applications/Docker.app'
==> Purging files for version 4.19.0,106363 of Cask docker
Error: It seems there is already a Binary at '/usr/local/share/zsh/site-functions/_docker'.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:62:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/binary.rb:13:in `link'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/symlinked.rb:23:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:235:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:228:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
~$
```

### Output of `brew doctor` and `brew config`

```shell
~$ brew doctor
Your system is ready to brew.
~$ brew config
HOMEBREW_VERSION: 4.0.15-97-ge191b82
ORIGIN: https://github.com/Homebrew/brew
HEAD: e191b827cce991f52be36b0a8fc3daed3ef66143
Last commit: 40 minutes ago
Core tap JSON: 28 Apr 07:59 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 12.6.5-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
~$
```

### Output of `brew tap`

```shell
~$ brew tap
homebrew/cask
null-dev/firefox-profile-switcher
~$
```

### PR DESCRIPTION
**Pull request by osalbahr**
The added caveat should clarify how to add the CLI tools after installing the cask.

Fixes [#46078 (comment)](https://github.com/Homebrew/homebrew-cask/issues/146078#issuecomment-1527319437)

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online docker` is error-free.
- [x] `brew style --fix docker` reports no offenses.

Commands log:

  ```
homebrew-cask$ brew audit --cask --online docker
==> Downloading https://desktop.docker.com/mac/main/amd64/106363/Docker.dmg
Already downloaded: /Users/osos/Library/Caches/Homebrew/downloads/a2fa53b312129a06f0f442d39dc52e4aa215dd8202dccd10ade7522d8fdd9584--Docker.dmg
homebrew-cask$ brew style --fix docker

1 file inspected, no offenses detected
homebrew-cask$ git branch
* add-docker-cli-caveat
  master
homebrew-cask$ git status
On branch add-docker-cli-caveat
Your branch is up to date with 'origin/add-docker-cli-caveat'.

nothing to commit, working tree clean
homebrew-cask$ 
  ```

### CODE REVIEW

**Review by razvanazamfirei — APPROVED** [review]

File: Casks/docker.rb [hunk 1]
```diff
@@ -116,8 +116,14 @@
       ]
 
   caveats <<~EOS
+    CLI tools are installed after launching Docker. They will be symlinked to one of the following
+    based on your preference:
```
Comment (osalbahr) [inline Casks/docker.rb:120]: I like your updated caveat. It's more concise and conveys more information.

I just tried to install the cask just to see how it would look like. Is the newline before "based" intended?

Screen Shot 2023-05-04 at 9 39 40 AM

Comment (razvanazamfirei) [reply Casks/docker.rb:120]: Thank you! Yes, the line break was intentional as not all terminals line-wrap. I'll change it in the next update so it breaks at 80 char instead of 100.
