### PR TITLE
Remove launchjob files during uninstall, even if they are not loaded

### LINKED ISSUE #14728: Launchctl uninstall do not clean-up users LaunchAgents .plist files
(moving discussion from #14723)

launchctl uninstall seems to be designed to delete LaunchAgents .plist files as well, but it does not work on users LaunchAgents.
[/lib/hbc/artifact/uninstall_base.rb#L215-L223](../blob/c0ed120631bd6ab5607d99dfa0efff82b7398959/lib/hbc/artifact/uninstall_base.rb#L215-L223):
```ruby
if result.success?
  paths = ["/Library/LaunchAgents/#{service}.plist",
           "/Library/LaunchDaemons/#{service}.plist"]
  paths.each { |elt| elt.prepend('~') } unless with_sudo
  paths = paths.map { |elt| Pathname(elt) }.select(&:exist?)
  paths.each do |path|
    @command.run!('/bin/rm', :args => ['-f', '--', path], :sudo => with_sudo)
  end
end
```

Issue seems to be related to FileTest.exist not supporting tilde:
```ruby
irb(main):001:0> FileTest.exist?('./')
=> true
irb(main):002:0> FileTest.exist?('~/')
=> false
```

CC @vitorgalvao, @jawshooah

### PR DESCRIPTION
**Pull request by jawshooah**
This fixes the original implementation in #8523 to correctly remove user launchjob files, and to do so even when the jobs have not been loaded.

Fixes #14728

[Review on Reviewable](https://reviewable.io/reviews/caskroom/homebrew-cask/14730)

### CODE REVIEW

File: lib/hbc/artifact/uninstall_base.rb [hunk 1]
```diff
@@ -209,18 +209,16 @@ def dispatch_uninstall_directives(stanza, expand_tilde=true)
...
+          paths = ["/Library/LaunchAgents/#{service}.plist",
+                   "/Library/LaunchDaemons/#{service}.plist"]
+          paths.each { |elt| elt.prepend(ENV['HOME']) } unless with_sudo
+          paths = paths.map { |elt| Pathname(elt) }.select(&:exist?)
+          paths.each do |path|
+            @command.run!('/bin/rm', :args => ['-f', '--', path], :sudo => with_sudo)
+          end
           plist_status = @command.run('/bin/launchctl', :args => ['list', service], :sudo => with_sudo, :print_stderr => false).stdout
           if %r{^\{}.match(plist_status)
             result = @command.run!('/bin/launchctl', :args => ['remove', service], :sudo => with_sudo)
```
Comment (forkbomber) [inline lib/hbc/artifact/uninstall_base.rb]: @jawshooah any specific reason to rm .plist file and only after it run `launchctl remove`?
This is a reversal of previous flow and feels unnatural.
I'd assume it works just fine, but we can't safely assume that another launchctl rewrite at Apple wouldn't break our sequence (i. e. first `rm .plist` and only then `launchctl remove`).

Comment (jawshooah) [inline lib/hbc/artifact/uninstall_base.rb]: Good point. I tested locally and there were no problems, but there's no guarantee that won't change. Thanks for the review!

**Comment by vitorgalvao** [comment]
Looks fine to me. We should cut a release after this is in (there were other small fixes in the meantime as well)

**Comment by vitorgalvao** [comment]
Are you cutting the new release, or do you want me to do it?

**Comment by jawshooah** [comment]
Took care of it myself.
