### PR TITLE
spyder: update uninstall and zap directories

### LINKED ISSUE #232898: Issue with spyder cask upgrade
### Verification

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/HEAD/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

When trying to update spyder via brew, it always results in a situation where it fails and will say that the location where spyder-6 is installed is not empty. the only way to rectify this after a failed update attempt is to do an rm -rf on the /System/Volumes/Data/Library/spyder-6 directory

The issue is specifically with the way in which the spyder package installer works, this needs to have the folder removed before it can be updated / reinstalled

### Command that failed

brew up

### Output of command with `--verbose --debug`

```shell
brew install --cask --adopt spyder --verbose --debug
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading spyder
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://github.com/spyder-ide/spyder/releases/download/v6.1.0/Spyder-macOS-arm64.pkg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.6.17-63-g085edfc\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 26.0.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 -V
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.6.17-63-g085edfc\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 26.0.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/spyder-ide/spyder/releases/download/v6.1.0/Spyder-macOS-arm64.pkg
Already downloaded: /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -target arm64-apple-macosx26 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg
==> /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg is quarantined
==> Verifying checksum for '50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg'
/usr/bin/env hdiutil imageinfo -format /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg
==> Installing Cask spyder
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Pkg for /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg
cp -p /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg /opt/homebrew/Caskroom/spyder/6.1.0/Spyder-macOS-arm64.pkg
==> Verifying Gatekeeper status of /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg
==> /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg is quarantined
==> Propagating quarantine from /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg to /opt/homebrew/Caskroom/spyder/6.1.0
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0381\;68e0dfc8\;\;F4E354B1-79A3-424A-8DF1-D1A8065787A1
==> Creating metadata directory: /opt/homebrew/Caskroom/spyder/.metadata/6.1.0/20251020020702.866
==> Creating metadata subdirectory: /opt/homebrew/Caskroom/spyder/.metadata/6.1.0/20251020020702.866/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for spyder with `sudo` (which may request your password)...
/usr/bin/sudo -u root -E LOGNAME=alexgadd USER=alexgadd USERNAME=alexgadd -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/spyder/6.1.0/Spyder-macOS-arm64.pkg -target / -verboseR
Password:
installer: Package name is Spyder 6.1.0
installer: Upgrading at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Spyder 6.1.0…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%4.557750
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:%24.669935
installer:PHASE:Writing files…
installer:%38.497435
installer:PHASE:Writing files…
installer:%48.176685
installer:PHASE:Writing files…
installer:%56.473184
installer:PHASE:Writing files…
installer:%65.408262
installer:PHASE:Running package scripts…
installer:%66.100082
installer:PHASE:Running package scripts…
installer:%66.788975
installer:PHASE:Running package scripts…
installer:%67.485393
installer:PHASE:Running package scripts…
installer:%68.173048
installer:PHASE:Running package scripts…
installer:%68.865529
installer:PHASE:Running package scripts…
installer:%69.558979
installer:PHASE:Running package scripts…
installer:%69.609309
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The upgrade failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “Spyder-macOS-arm64.pkg”.)
==> Purging files for version 6.1.0 of Cask spyder
Error: Failure while executing; `/usr/bin/sudo -u root -E LOGNAME=alexgadd USER=alexgadd USERNAME=alexgadd -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/spyder/6.1.0/Spyder-macOS-arm64.pkg -target / -verboseR` exited with 1. Here's the output:
installer: Package name is Spyder 6.1.0
installer: Upgrading at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing Spyder 6.1.0…
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%4.557750
installer:PHASE:Writing files…
installer:PHASE:Writing files…
installer:%24.669935
installer:PHASE:Writing files…
installer:%38.497435
installer:PHASE:Writing files…
installer:%48.176685
installer:PHASE:Writing files…
installer:%56.473184
installer:PHASE:Writing files…
installer:%65.408262
installer:PHASE:Running package scripts…
installer:%66.100082
installer:PHASE:Running package scripts…
installer:%66.788975
installer:PHASE:Running package scripts…
installer:%67.485393
installer:PHASE:Running package scripts…
installer:%68.173048
installer:PHASE:Running package scripts…
installer:%68.865529
installer:PHASE:Running package scripts…
installer:%69.558979
installer:PHASE:Running package scripts…
installer:%69.609309
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The upgrade failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “Spyder-macOS-arm64.pkg”.)
/opt/homebrew/Library/Homebrew/system_command.rb:500:in 'SystemCommand::Result#assert_success!'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/call_validation_2_7.rb:652:in 'UnboundMethod#bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/call_validation_2_7.rb:652:in 'block in SystemCommand::Result#create_validator_procedure_fast0'
/opt/homebrew/Library/Homebrew/system_command.rb:162:in 'SystemCommand#run!'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/call_validation_2_7.rb:59:in 'UnboundMethod#bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/call_validation_2_7.rb:59:in 'block in SystemCommand#create_validator_method_fast0'
/opt/homebrew/Library/Homebrew/system_command.rb:104:in 'SystemCommand.run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/call_validation.rb:179:in 'UnboundMethod#bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/call_validation.rb:179:in 'T::Private::Methods::CallValidation.validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/call_validation.rb:121:in 'block in SystemCommand.create_validator_slow_skip_block_type'
/opt/homebrew/Library/Homebrew/system_command.rb:129:in 'SystemCommand.run!'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/call_validation.rb:179:in 'UnboundMethod#bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/call_validation.rb:179:in 'T::Private::Methods::CallValidation.validate_call_skip_block_type'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/call_validation.rb:121:in 'block in SystemCommand.create_validator_slow_skip_block_type'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:63:in 'block in Cask::Artifact::Pkg#run_installer'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:76:in 'Cask::Artifact::Pkg#with_choices_file'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:56:in 'Cask::Artifact::Pkg#run_installer'
/opt/homebrew/Library/Homebrew/cask/artifact/pkg.rb:32:in 'Cask::Artifact::Pkg#install_phase'
/opt/homebrew/Library/Homebrew/cask/installer.rb:344:in 'block in Cask::Installer#install_artifacts'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:15:in 'Array#each'
/opt/homebrew/Library/Homebrew/cask/artifact_set.rb:15:in 'Cask::ArtifactSet#each'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/call_validation_2_7.rb:652:in 'UnboundMethod#bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/call_validation_2_7.rb:652:in 'block in Cask::ArtifactSet#create_validator_procedure_fast0'
/opt/homebrew/Library/Homebrew/cask/installer.rb:323:in 'Cask::Installer#install_artifacts'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/call_validation.rb:282:in 'UnboundMethod#bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/call_validation.rb:282:in 'T::Private::Methods::CallValidation.validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/_methods.rb:259:in 'block in Cask::Installer#_on_method_added'
/opt/homebrew/Library/Homebrew/cask/installer.rb:168:in 'Cask::Installer#install'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/call_validation.rb:282:in 'UnboundMethod#bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/call_validation.rb:282:in 'T::Private::Methods::CallValidation.validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/_methods.rb:259:in 'block in Cask::Installer#_on_method_added'
/opt/homebrew/Library/Homebrew/cmd/install.rb:289:in 'block in Homebrew::Cmd::InstallCmd#run'
/opt/homebrew/Library/Homebrew/cmd/install.rb:278:in 'Array#each'
/opt/homebrew/Library/Homebrew/cmd/install.rb:278:in 'Homebrew::Cmd::InstallCmd#run'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/call_validation.rb:282:in 'UnboundMethod#bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/call_validation.rb:282:in 'T::Private::Methods::CallValidation.validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/sorbet-runtime-0.6.12649/lib/types/private/methods/_methods.rb:259:in 'block in Homebrew::Cmd::InstallCmd#_on_method_added'
/opt/homebrew/Library/Homebrew/brew.rb:101:in '<main>'
➜  Downloads brew install --cask --adopt spyder --verbose --debug
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromAPILoader): loading spyder
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://github.com/spyder-ide/spyder/releases/download/v6.1.0/Spyder-macOS-arm64.pkg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.6.17-63-g085edfc\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 26.0.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 -V
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.6.17-63-g085edfc\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 26.0.1\)\ curl/8.7.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://github.com/spyder-ide/spyder/releases/download/v6.1.0/Spyder-macOS-arm64.pkg
Already downloaded: /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg
==> Checking quarantine support
/usr/bin/env /usr/bin/xattr -h
/usr/bin/env /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -target arm64-apple-macosx26 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg
==> /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg is quarantined
==> Verifying checksum for '50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg'
/usr/bin/env hdiutil imageinfo -format /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg
==> Installing Cask spyder
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Pkg for /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg
cp -p /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg /opt/homebrew/Caskroom/spyder/6.1.0/Spyder-macOS-arm64.pkg
==> Verifying Gatekeeper status of /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg
==> /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg is quarantined
==> Propagating quarantine from /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg to /opt/homebrew/Caskroom/spyder/6.1.0
/usr/bin/env /usr/bin/xattr -p com.apple.quarantine /Users/alexgadd/Library/Caches/Homebrew/downloads/50dd98e9d49a25bd648b4cd6b2fd0b67a06ce5d8e1dcf5c821ef8a4c2ae306c6--Spyder-macOS-arm64.pkg
/usr/bin/env /usr/bin/xargs -0 -- /bin/chmod -h u+w
/usr/bin/env /usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0381\;68e0dfc8\;\;F4E354B1-79A3-424A-8DF1-D1A8065787A1
==> Creating metadata directory: /opt/homebrew/Caskroom/spyder/.metadata/6.1.0/20251020021009.088
==> Creating metadata subdirectory: /opt/homebrew/Caskroom/spyder/.metadata/6.1.0/20251020021009.088/Casks
==> Installing artifacts
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for spyder with `sudo` (which may request your password)...
/usr/bin/sudo -u root -E LOGNAME=alexgadd USER=alexgadd USERNAME=alexgadd -- /usr/sbin/installer -pkg /opt/homebrew/Caskroom/spyder/6.1.0/Spyder-macOS-arm64.pkg -target / -verboseR
Password:
sudo: a password is required
```

### Output of `brew doctor` and `brew config`

```shell
nothing from brew doctor

brew link flux
Linking /opt/homebrew/Cellar/flux/0.198.0... 4 symlinks created.
➜  Downloads sudo upgrade
Password:
sudo: upgrade: command not found
➜  Downloads brew upgrade
➜  Downloads brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  enjoyable
  qbittorrent
  themeengine

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libdvdcss.2.dylib
➜  Downloads brew config
HOMEBREW_VERSION: 4.6.17-63-g085edfc
ORIGIN: https://github.com/Homebrew/brew
HEAD: 085edfc8bb2ea5783586ae71e6c4bdb7c26fcd40
Last commit: 5 hours ago
Branch: main
Core tap HEAD: 8a5c42dfe6cd0b769ec082e855191a276123a9d2
Core tap last commit: 8 hours ago
Core tap JSON: 20 Oct 02:11 UTC
Core cask tap HEAD: 2505dbf29e3df27ef1dab17f5f4c4d7a7ea3656b
Core cask tap last commit: 8 hours ago
Core cask tap JSON: 20 Oct 02:11 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_FORBID_PACKAGES_FROM_PATHS: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.4.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.5/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 17.0.0 build 1700
Git: 2.50.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 26.0.1-arm64
CLT: 26.0.0.0.1.1757719676
Xcode: 26.0.1
Rosetta 2: false
```

### Output of `brew tap`

```shell
homebrew/cask
homebrew/core
```

### PR DESCRIPTION
**Pull request by AlexGadd**
In order to uninstall this application and to be able to reinstall again (ever) the following folder must be removed: "/System/Volumes/Data/Library/spyder-6"

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

Closes #232898

### CODE REVIEW

**Comment by AlexGadd** [comment]
I don't know if this will fix upgrade issues, but it does at least fix the uninstall issues

File: Casks/s/spyder.rb [hunk 1]
```diff
@@ -26,9 +26,11 @@
               "/Applications/REQUIRED.app",
               "/Applications/Spyder #{version.major} Uninstaller.app",
               "/Applications/Spyder #{version.major}.app",
+              "/System/Volumes/Data/Library/spyder-6",
```
Comment (bevanjkay) [inline Casks/s/spyder.rb]:
```suggestion
              "/System/Volumes/Data/Library/spyder-#{version.major}",
```

File: Casks/s/spyder.rb [hunk 2]
```diff
@@ -26,9 +26,11 @@
...
             ]
 
   zap trash: [
+    "/System/Volumes/Data/Library/spyder-6",
```
Comment (bevanjkay) [inline Casks/s/spyder.rb]:
```suggestion
```

This does not need to be included here because it is already in the uninstall stanza.

**Comment by AlexGadd** [comment]
Thanks, I've accepted your suggestions

File: Casks/s/spyder.rb [hunk 3]
```diff
@@ -26,6 +26,7 @@
               "/Applications/REQUIRED.app",
               "/Applications/Spyder #{version.major} Uninstaller.app",
               "/Applications/Spyder #{version.major}.app",
+              "/System/Volumes/Data/Library/spyder-#{version.major}",
```
Comment (bevanjkay) [inline Casks/s/spyder.rb]:
```suggestion
              "/Library/spyder-#{version.major}",
```

Sorry, I missed that we should just link directly to the folder, not through `/System/Volumes/Data/`

Comment (AlexGadd) [reply Casks/s/spyder.rb]: all good, accepting the change

**Review by khipp — APPROVED** [review]
