### PR TITLE
soundtoys 5.4.0.17121

### LINKED ISSUE #147672: Soundtoys bump-cask-pr
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Attempted to request a soundtoys update with the bump-cask-pr command, but it looks like the url field in the soundtoys.rb file needs to be updated as it no longer matches the new url.

This is the soundtoys.rb url field:
  url "https://storage.googleapis.com/soundtoys-download/versions/version_#{version.dots_to_underscores}/Soundtoys#{version.major}_#{version}.dmg",

This is the new soundtoys url:
https://storage.googleapis.com/soundtoys-download/versions/version_5_4_0_17121/SoundtoysV54Bundle_5.4.0.17121.dmg

### Command that failed

brew bump-cask-pr soundtoys --version 5.4.0.17121 --verbose --debug

### Output of command with `--verbose --debug`

```shell
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/bin/bundle clean
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromDefaultTapPathLoader): loading soundtoys
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.19-7-ga29b22f\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/issues\?q=soundtoys\+is\%3Apr\+repo\%3AHomebrew\%2Fhomebrew-cask\+state\%3Aopen\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github\+json --write-out '
'\%\{http_code\} --header X-GitHub-Api-Version:2022-11-28 --dump-header /private/tmp/github_api_headers20230522-91469-y3mvsv
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.19-7-ga29b22f\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/issues\?q=soundtoys\+5.4.0.17121\+is\%3Apr\+repo\%3AHomebrew\%2Fhomebrew-cask\+state\%3Aclosed\+in\%3Atitle\&per_page=100 --header Accept:\ application/vnd.github\+json --write-out '
'\%\{http_code\} --header X-GitHub-Api-Version:2022-11-28 --dump-header /private/tmp/github_api_headers20230522-91469-1iac3r0
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromContentLoader): loading cask "soundtoys" do
  version "5.4.0.17121"
  sha256 "8c9d6243f1511952c79769030383b06afeb36ad688d303366e10b1c4eea450e5"

  url "https://storage.googleapis.com/soundtoys-download/versions/version_#{version.dots_to_underscores}/Soundtoys#{version.major}_#{version}.dmg",
      verified: "storage.googleapis.com/soundtoys-download/"
  name "Soundtoys"
  desc "Audio Effects Plugins"
  homepage "https://www.soundtoys.com/product/soundtoys/"

  livecheck do
    url "https://storage.googleapis.com/soundtoys-download/download.json"
    strategy :json do |json|
      json["Soundtoys5_Mac"]["fullversion"]
    end
  end

  pkg "Install Soundtoys #{version.major}.pkg"

  uninstall pkgutil:   ["com.soundtoys.*", "com.paceap.pkg.eden.*"],
            launchctl: ["com.paceap.eden.licensed", "com.paceap.eden.licensed.agent"]
end
/opt/homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromContentLoader): loading cask "soundtoys" do
  version "5.4.0.17121"
  sha256 "8c9d6243f1511952c79769030383b06afeb36ad688d303366e10b1c4eea450e5"

  url "https://storage.googleapis.com/soundtoys-download/versions/version_#{version.dots_to_underscores}/Soundtoys#{version.major}_#{version}.dmg",
      verified: "storage.googleapis.com/soundtoys-download/"
  name "Soundtoys"
  desc "Audio Effects Plugins"
  homepage "https://www.soundtoys.com/product/soundtoys/"

  livecheck do
    url "https://storage.googleapis.com/soundtoys-download/download.json"
    strategy :json do |json|
      json["Soundtoys5_Mac"]["fullversion"]
    end
  end

  pkg "Install Soundtoys #{version.major}.pkg"

  uninstall pkgutil:   ["com.soundtoys.*", "com.paceap.pkg.eden.*"],
            launchctl: ["com.paceap.eden.licensed", "com.paceap.eden.licensed.agent"]
end
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.19-7-ga29b22f\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://storage.googleapis.com/soundtoys-download/versions/version_5_4_0_17121/Soundtoys5_5.4.0.17121.dmg
/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.19-7-ga29b22f\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://storage.googleapis.com/soundtoys-download/versions/version_5_4_0_17121/Soundtoys5_5.4.0.17121.dmg
Error: Download failed on Cask 'soundtoys' with message: Failure while executing; `/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.19-7-ga29b22f\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://storage.googleapis.com/soundtoys-download/versions/version_5_4_0_17121/Soundtoys5_5.4.0.17121.dmg` exited with 22. Here's the output:
HTTP/2 404 
x-guploader-uploadid: ADPycdtPgObu6T7bP6Tj7AyNe5ZdRVAGEy-0fZaeac3MlgSochQ_XgCG4cQix1orO2O0qwAYZaQlOMaTNJ6Hflvyr_o6uw
content-type: application/xml; charset=UTF-8
content-length: 236
date: Mon, 22 May 2023 21:35:23 GMT
expires: Mon, 22 May 2023 21:35:23 GMT
cache-control: private, max-age=0
server: UploadServer
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

curl: (22) The requested URL returned error: 404

/opt/homebrew/Library/Homebrew/system_command.rb:313:in `assert_success!'
/opt/homebrew/Library/Homebrew/utils/curl.rb:230:in `block in curl_headers'
/opt/homebrew/Library/Homebrew/utils/curl.rb:208:in `each'
/opt/homebrew/Library/Homebrew/utils/curl.rb:208:in `curl_headers'
/opt/homebrew/Library/Homebrew/download_strategy.rb:484:in `resolve_url_basename_time_file_size'
/opt/homebrew/Library/Homebrew/download_strategy.rb:472:in `resolved_url_and_basename'
/opt/homebrew/Library/Homebrew/download_strategy.rb:323:in `resolved_basename'
/opt/homebrew/Library/Homebrew/download_strategy.rb:307:in `cached_location'
/opt/homebrew/Library/Homebrew/download_strategy.rb:280:in `temporary_path'
/opt/homebrew/Library/Homebrew/download_strategy.rb:405:in `fetch'
/opt/homebrew/Library/Homebrew/downloadable.rb:87:in `fetch'
/opt/homebrew/Library/Homebrew/cask/download.rb:51:in `fetch'
/opt/homebrew/Library/Homebrew/dev-cmd/bump-cask-pr.rb:167:in `block (3 levels) in bump_cask_pr'
/opt/homebrew/Library/Homebrew/dev-cmd/bump-cask-pr.rb:155:in `each'
/opt/homebrew/Library/Homebrew/dev-cmd/bump-cask-pr.rb:155:in `block (2 levels) in bump_cask_pr'
/opt/homebrew/Library/Homebrew/simulate_system.rb:29:in `with'
/opt/homebrew/Library/Homebrew/dev-cmd/bump-cask-pr.rb:152:in `block in bump_cask_pr'
/opt/homebrew/Library/Homebrew/dev-cmd/bump-cask-pr.rb:151:in `each'
/opt/homebrew/Library/Homebrew/dev-cmd/bump-cask-pr.rb:151:in `bump_cask_pr'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

### Output of `brew doctor` and `brew config`

```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /opt/homebrew/Library/Taps/homebrew/homebrew-core && git stash -u && git clean -d -f

Uncommitted files:
  ?? .DS_Store

_____________________

brew config
HOMEBREW_VERSION: 4.0.19-7-ga29b22f
ORIGIN: https://github.com/Homebrew/brew
HEAD: a29b22f1a2e12621a6139f72dc70575b5619d086
Last commit: 9 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 927bcd73dc9272dfa1936bbcbf109f275759204e
Core tap last commit: 2 hours ago
Core tap branch: master
Core tap JSON: 22 May 21:25 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.3-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
brew tap

homebrew/cask
homebrew/core
```

### PR DESCRIPTION
**Pull request by miccal**
Closes https://github.com/Homebrew/homebrew-cask/issues/147672

### CODE REVIEW

File: Casks/soundtoys.rb [hunk 1]
```diff
@@ -1,22 +1,30 @@
...
+      verified: "storage.googleapis.com/soundtoys-download/versions/"
   name "Soundtoys"
   desc "Audio Effects Plugins"
   homepage "https://www.soundtoys.com/product/soundtoys/"
 
   livecheck do
     url "https://storage.googleapis.com/soundtoys-download/download.json"
     strategy :json do |json|
-      json["Soundtoys5_Mac"]["fullversion"]
+      json["SoundtoysV#{version.major_minor.no_dots}Bundle_Mac"]["fullversion"]
```
Comment (samford) [inline Casks/soundtoys.rb:14]:
```suggestion
      json.map do |key, item|
        next unless key.match?(/Soundtoys.*?[._-]Mac/i)

        item["fullversion"]
      end
```

**Review by samford — COMMENTED** [review]
`json["SoundtoysV#{version.major_minor.no_dots}Bundle_Mac"]["fullversion"]` is tied to the current cask version, so it won't work for versions above 5.4.x. Instead, we have to identify the `soundtoys` Mac version in a version-independent manner.

There are a few possible ways to approach this but the suggestion below simply looks for a key that includes `Soundtoys` and `_Mac` (case insensitive) and then uses any `fullversion` value.

Alternatively, we could select item(s) based on the `product`, `title`, `platform`, etc. or simply match within the `url` using a regex. They all seem roughly equal, so this suggestion would work for now and we can always revisit it if we run into problems.

File: Casks/soundtoys.rb (hunk 1 above)
Comment (miccal) [reply Casks/soundtoys.rb]: Thanks @samford.

**Review by bevanjkay — APPROVED** [review]
