### PR TITLE
ibm-aspera-connect: fix uninstall script path and move log deletion to zap

### LINKED ISSUE #99043: IBM Aspera Connect cannot be uninstalled: No such file or directory
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

`brew uninstall ibm-aspera-connect` fails with:
```
Error: Failure while executing; `\~/Library/Application\ Support/Aspera/Aspera\ Connect/uninstall_connect.sh -f` exited with 127. Here's the output:
No such file or directory - ~/Library/Application Support/Aspera/Aspera Connect/uninstall_connect.sh
```

The correct path to the uninstall script seems to match what is shown (except the leading backlash `\`):
```
~/Library/Application\ Support/Aspera/Aspera\ Connect/uninstall_connect.sh
```

#### Command that failed

```
~ ❯ brew uninstall ibm-aspera-connect

==> Uninstalling Cask ibm-aspera-connect
==> Running uninstall script ~/Library/Application Support/Aspera/Aspera Connect
Error: Failure while executing; `\~/Library/Application\ Support/Aspera/Aspera\ Connect/uninstall_connect.sh -f` exited with 127. Here's the output:
No such file or directory - ~/Library/Application Support/Aspera/Aspera Connect/uninstall_connect.sh
```

#### Output of command with `--verbose --debug`

```
~ ❯ brew uninstall ibm-aspera-connect --verbose --debug
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/lame.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gmp.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cppcheck.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gh.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zsh-autosuggestions.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libpng.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ncurses.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cmake.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/opus.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mpfr.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/highlight.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libvorbis.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/starship.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sox.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/rustup-init.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/clang-format.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libyaml.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libogg.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/circleci.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/readline.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/lcov.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nvm.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/lua.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/htop.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openjdk.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mad.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/flac.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/signal-cli.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/shellcheck.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bfg.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/isl.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pcre.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/portaudio.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fltk.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/opusfile.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/jpeg.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/zsh-syntax-highlighting.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libsndfile.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ruby.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/restic.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libmpc.rb
==> Uninstalling Cask ibm-aspera-connect
==> Uninstalling Cask ibm-aspera-connect
==> Uninstalling artifacts
==> 2 artifacts defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007fd24516ad18 @cask=#<Cask::Cask:0x00007fd2451498c0 @token="ibm-aspera-connect", @sourcefile_path=#<Pathname:/usr/local/Caskroom/ibm-aspera-connect/.metadata/3.10.1.181943/20210105131226.918/Casks/ibm-aspera-connect.rb>, @tap=nil, @block=#<Proc:0x00007fd245149730@/usr/local/Caskroom/ibm-aspera-connect/.metadata/3.10.1.181943/20210105131226.918/Casks/ibm-aspera-connect.rb:1>, @default_config=#<Cask::Config:0x00007fd2451496e0 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/ibm-aspera-connect>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/ibm-aspera-connect/.metadata>, @config=#<Cask::Config:0x00007fd24915e6b8 @explicit={}, @default={:languages=>["en-GB", "en-DE", "de-DE", "en"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Users/chohner/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Users/chohner/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/chohner/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Users/chohner/Library/Spotlight>, :dictionarydir=>#<Pathname:/Users/chohner/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/chohner/Library/Fonts>, :servicedir=>#<Pathname:/Users/chohner/Library/Services>, :input_methoddir=>#<Pathname:/Users/chohner/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/chohner/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/chohner/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/chohner/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/chohner/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/chohner/Library/Screen Savers>}, @env={}>, @dsl=#<Cask::DSL:0x00007fd249166c00 @cask=#<Cask::Cask:0x00007fd2451498c0 ...>, @token="ibm-aspera-connect", @version="3.10.1.181943", @sha256=#<Checksum:0x00007fd249166840 @hexdigest="aff234db6ce414044a7932926137a8f451dd6bcc026c1b5f067283d43e1d18c7">, @url=#<URL:0x00007fd249165aa8 @uri=#<URI::HTTPS https://d3gcli72yxqn2z.cloudfront.net/connect_3_10_1_181943_ga/v4/bin/IBMAsperaConnectInstallerOneClick-3.10.1.181943.dmg>, @verified="d3gcli72yxqn2z.cloudfront.net/", @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:verified=>"d3gcli72yxqn2z.cloudfront.net/", :user_agent=>:default}, @from_block=false, @caller_location="/usr/local/Caskroom/ibm-aspera-connect/.metadata/3.10.1.181943/20210105131226.918/Casks/ibm-aspera-connect.rb:5:in `block in load'">, @name=["IBM Aspera Connect"], @desc="Facilitate uploads and downloads with an Aspera transfer server", @homepage="https://www.ibm.com/aspera/connect/", @artifacts=#<SortedSet: {...}>, @language_eval=nil, @appcast=#<Cask::DSL::Appcast:0x00007fd249164ea0 @uri=#<URI::HTTPS https://www.ibm.com/aspera/connect/>, @parameters={:must_contain=>"3_10_1_181943"}, @must_contain="3_10_1_181943">>>, @directives={:script=>{:executable=>"~/Library/Application Support/Aspera/Aspera Connect/uninstall_connect.sh", :args=>["-f"]}, :delete=>"~/Library/Logs/Aspera_Connect", :signal=>[]}>, #<Cask::Artifact::Installer:0x00007fd24516b880 @cask=#<Cask::Cask:0x00007fd2451498c0 @token="ibm-aspera-connect", @sourcefile_path=#<Pathname:/usr/local/Caskroom/ibm-aspera-connect/.metadata/3.10.1.181943/20210105131226.918/Casks/ibm-aspera-connect.rb>, @tap=nil, @block=#<Proc:0x00007fd245149730@/usr/local/Caskroom/ibm-aspera-connect/.metadata/3.10.1.181943/20210105131226.918/Casks/ibm-aspera-connect.rb:1>, @default_config=#<Cask::Config:0x00007fd2451496e0 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/ibm-aspera-connect>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/ibm-aspera-connect/.metadata>, @config=#<Cask::Config:0x00007fd24915e6b8 @explicit={}, @default={:languages=>["en-GB", "en-DE", "de-DE", "en"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Users/chohner/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Users/chohner/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/chohner/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Users/chohner/Library/Spotlight>, :dictionarydir=>#<Pathname:/Users/chohner/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/chohner/Library/Fonts>, :servicedir=>#<Pathname:/Users/chohner/Library/Services>, :input_methoddir=>#<Pathname:/Users/chohner/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/chohner/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/chohner/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/chohner/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/chohner/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/chohner/Library/Screen Savers>}, @env={}>, @dsl=#<Cask::DSL:0x00007fd249166c00 @cask=#<Cask::Cask:0x00007fd2451498c0 ...>, @token="ibm-aspera-connect", @version="3.10.1.181943", @sha256=#<Checksum:0x00007fd249166840 @hexdigest="aff234db6ce414044a7932926137a8f451dd6bcc026c1b5f067283d43e1d18c7">, @url=#<URL:0x00007fd249165aa8 @uri=#<URI::HTTPS https://d3gcli72yxqn2z.cloudfront.net/connect_3_10_1_181943_ga/v4/bin/IBMAsperaConnectInstallerOneClick-3.10.1.181943.dmg>, @verified="d3gcli72yxqn2z.cloudfront.net/", @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:verified=>"d3gcli72yxqn2z.cloudfront.net/", :user_agent=>:default}, @from_block=false, @caller_location="/usr/local/Caskroom/ibm-aspera-connect/.metadata/3.10.1.181943/20210105131226.918/Casks/ibm-aspera-connect.rb:5:in `block in load'">, @name=["IBM Aspera Connect"], @desc="Facilitate uploads and downloads with an Aspera transfer server", @homepage="https://www.ibm.com/aspera/connect/", @artifacts=#<SortedSet: {...}>, @language_eval=nil, @appcast=#<Cask::DSL::Appcast:0x00007fd249164ea0 @uri=#<URI::HTTPS https://www.ibm.com/aspera/connect/>, @parameters={:must_contain=>"3_10_1_181943"}, @must_contain="3_10_1_181943">>>, @path=#<Pathname:IBM Aspera Connect Installer.app>, @args=[]>}>
==> Uninstalling artifact of class Cask::Artifact::Uninstall
==> Running uninstall script ~/Library/Application Support/Aspera/Aspera Connect/uninstall_connect.sh
\~/Library/Application\ Support/Aspera/Aspera\ Connect/uninstall_connect.sh -f
Error: Failure while executing; `\~/Library/Application\ Support/Aspera/Aspera\ Connect/uninstall_connect.sh -f` exited with 127. Here's the output:
No such file or directory - ~/Library/Application Support/Aspera/Aspera Connect/uninstall_connect.sh
/usr/local/Homebrew/Library/Homebrew/system_command.rb:247:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:63:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:38:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:310:in `uninstall_script'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:76:in `dispatch_uninstall_directive'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:15:in `block in uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:14:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:470:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:467:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:416:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:61:in `block in uninstall_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:49:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:49:in `uninstall_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:69:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

#### Output of `brew doctor --verbose`

```
~ ❯ brew doctor --verbose
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.9.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/pry-0.13.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/method_source-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-4.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.4.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/commander-4.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/highline-2.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/colorize-0.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coderay-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/byebug-11.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/x86_64-darwin14
/usr/local/Homebrew/Library/Homebrew
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Homebrew Version
2.7.7-34-g0a46e34
==> macOS
10.15.7
==> SIP
Enabled
/usr/libexec/java_home --xml --failfast
==> Java
N/A
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3798 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (175 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1602 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (171 casks)
/usr/local/Homebrew/Library/Taps/mtslzr/homebrew-marmaduke-chromium (3 casks)
/usr/bin/xattr
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/Caskroom/miniconda/base/bin/icu-config
  /usr/local/Caskroom/miniconda/base/bin/freetype-config
  /usr/local/Caskroom/miniconda/base/bin/xslt-config
  /usr/local/Caskroom/miniconda/base/bin/libpng16-config
  /usr/local/Caskroom/miniconda/base/bin/libpng-config
  /usr/local/Caskroom/miniconda/base/bin/xml2-config
  /usr/local/Caskroom/miniconda/base/bin/python3-config
  /usr/local/Caskroom/miniconda/base/bin/ncursesw6-config
  /usr/local/Caskroom/miniconda/base/bin/python3.8-config
```

#### Output of `brew tap`

```
~ ❯ brew tap     
                         
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
mtslzr/marmaduke-chromium
vitorgalvao/tiny-scripts
```

### PR DESCRIPTION
**Pull request by cho-m**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

**Uninstall Output**
```console
❯ brew uninstall ibm-aspera-connect
==> Uninstalling Cask ibm-aspera-connect
==> Running uninstall script /Users/cho-m/Library/Application Support/Aspera/Aspera Connect/uninstall_connect.sh
forcing full uninstall
Uninstalling Aspera Connect for user cho-m
Keeping /Users/cho-m/Applications directory since it is not empty
Keeping /Users/cho-m/Library/Logs/Aspera_Connect directory since it is not empty
Aspera Connect has successfully been uninstalled
==> Purging files for version 3.11.1.58 of Cask ibm-aspera-connect
```

**Forced zap cleanup**
```console
❯ brew uninstall --cask --zap --force ibm-aspera-connect
==> Implied `brew uninstall --cask ibm-aspera-connect`
==> Running uninstall script /Users/cho-m/Library/Application Support/Aspera/Aspera Connect/uninstall_connect.sh
Warning: uninstall script /Users/cho-m/Library/Application Support/Aspera/Aspera Connect/uninstall_connect.sh does not exist; skipping.
==> Dispatching zap stanza
==> Trashing files:
~/Library/Application Scripts/com.aspera.connect.SafariExtension
~/Library/Application Scripts/com.aspera.drive.SendToExtension
~/Library/Containers/com.aspera.connect.SafariExtension
~/Library/Containers/com.aspera.drive.SendToExtension
~/Library/Group Containers/group.com.aspera.connect
~/Library/Logs/Aspera_Connect
~/Library/Preferences/com.aspera.connect.plist
~/Library/Saved Application State/com.aspera.connect.savedState
==> Removing all staged versions of Cask 'ibm-aspera-connect'

❯ ls ~/.Trash
 Aspera_Connect
 com.aspera.connect.SafariExtension
'com.aspera.connect.SafariExtension 14-09-39-193.SafariExtension'
 com.aspera.connect.savedState
 com.aspera.drive.SendToExtension
'com.aspera.drive.SendToExtension 14-09-39-194.SendToExtension'
 group.com.aspera.connect
 com.aspera.connect.plist
```

**Audit/Style**
```console
❯ brew audit --cask ibm-aspera-connect
audit for ibm-aspera-connect: passed

❯ brew style --fix ibm-aspera-connect

1 file inspected, no offenses detected
```

### CODE REVIEW

File: Casks/ibm-aspera-connect.rb [hunk 1]
```diff
@@ -17,8 +17,18 @@
   installer manual: "IBM Aspera Connect Installer.app"
 
   uninstall script: {
-    executable: "~/Library/Application Support/Aspera/Aspera Connect/uninstall_connect.sh",
+    executable: "#{ENV["HOME"]}/Library/Application Support/Aspera/Aspera Connect/uninstall_connect.sh",
```
Comment (vitorgalvao) [inline Casks/ibm-aspera-connect.rb:20]: Please keep this as `~`. This should be fixed at the source, not have different solutions for each cask.

**Review by vitorgalvao — CHANGES_REQUESTED** [review]

File: Casks/ibm-aspera-connect.rb (hunk 1 above)
Comment (cho-m) [reply Casks/ibm-aspera-connect.rb:20]: Created https://github.com/Homebrew/brew/pull/10956 for `~` support.
Will edit this in a bit.

**Review by vitorgalvao — APPROVED** [review]
