### PR TITLE
Fing: Fix slash in `version`.

### LINKED ISSUE #24872: fing not downloading
A few time ago, I had already installed the cask `fing` (version '3.0') with success.

I just noticed that now, cask as been renumbered (version '3.0,2016/09') and I tried to install with `brew cask install --force fing`

Unfortunately, although the download link looks correct (compared to the web site link that works), `brew cask` seems not to be able to download the file and raises this error:
```
==> Downloading https://39qiv73eht2y1az3q51pykkf-wpengine.netdna-ssl.com/wp-content/uploads/2016/09/overlook-fing-3.0.dmg_.zip
Error: Download failed on Cask 'fing' with message: No such file or directory - /Users/me/Library/Caches/Homebrew/Cask/fing--3.0,2016/09.zip.incomplete
```

P.S. Meantime I've no caching problem when installing other casks...

### PR DESCRIPTION
**Pull request by reitermarkus**
### Checklist
- [x] The commit message includes the cask’s name and version.
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
## 

Fixes https://github.com/caskroom/homebrew-cask/issues/24872.

### CODE REVIEW

File: Casks/fing.rb [hunk 1]
```diff
@@ -1,14 +1,14 @@
 cask 'fing' do
-  version '3.0,2016/09'
+  version '3.0,2016-09'
   sha256 'a8497ce00d58609d8677c6c7850e479420516d94e9f37d681dbdc970359294c6'
 
   # 39qiv73eht2y1az3q51pykkf-wpengine.netdna-ssl.com was verified as official when first introduced to the cask
-  url "https://39qiv73eht2y1az3q51pykkf-wpengine.netdna-ssl.com/wp-content/uploads/#{version.after_comma}/overlook-fing-#{version.before_comma}.dmg_.zip"
+  url "https://39qiv73eht2y1az3q51pykkf-wpengine.netdna-ssl.com/wp-content/uploads/#{version.after_comma.gsub("-", "/")}/overlook-fing-#{version.before_comma}.dmg_.zip"
```
Comment (jawshooah) [inline Casks/fing.rb]: Could use `hyphens_to_slashes` here

**Review by jawshooah — CHANGES_REQUESTED** [review]

File: Casks/fing.rb (hunk 1 above)
Comment (reitermarkus) [inline Casks/fing.rb]: Right, I didn't actually check if we had `slashes` in the DSL, since I had never seen a version with slashes before.
