### PR TITLE
persepolis-download-manager: deprecate, url change

### LINKED ISSUE #1101: Homebrew cask url incorrect since 5.2.0
I could not immediately find where or why it happened, but since v5.2.0 the release URL for MacOS does not seem to have an architecture (`_x64`) appended to it. This makes the [Homebrew cask](https://github.com/Homebrew/homebrew-cask/blob/bb8777b72c9727787a3718d2dfc25c96848010f5/Casks/p/persepolis-download-manager.rb) download fail. Not sure on which end this should be solved.

### PR DESCRIPTION
**Pull request by gellis12**
Persepolis-download-manager no longer uses separate arm and x86 buids as of 5.2.0, this commit closes persepolisdm/persepolis#1101

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-cask+is%3Aclosed+is%3Aunmerged+&type=pullrequests) (add your cask's name to the end of the search field).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by gellis12** [comment]
Note that the CI failures are related to the app not being notarized by Apple; this has been raised in a separate issue at persepolisdm/persepolis#962, and the dev has indicated that they are looking into a fix.

File: Casks/p/persepolis-download-manager.rb [hunk 1]
```diff
@@ -16,10 +13,16 @@
     strategy :github_latest
   end
 
+  deprecate! date: "2025-12-20", because: :fails_gatekeeper_check
```
Comment (krehel) [inline Casks/p/persepolis-download-manager.rb]: Set the date to 2026-09-01 and `disable!`, this is what we have been doing specifically for unsigned Casks to set a consistent future date.

```suggestion
  disable! date: "2026-09-01", because: :fails_gatekeeper_check
```

**Review by bevanjkay — APPROVED** [review]
