### PR TITLE
Faster downloads for burp-suite and burp-suite-professional

### LINKED ISSUE #167997: Downloads for burp suite & calibre are exceptionally slow
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [ ] I ran `brew update-reset && brew update` and retried my command.
- [ ] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

Calibre & burp suite download way too slow. Here in India at-least, it takes hours to upgrade just these two casks always.

Calibre website allows alternate downloads from their official github releases and portswigger website uses a CDN domain to download really really fast.

So casks should do the same as well.

### Command that failed

N/A

### Output of command with `--verbose --debug`

```shell
N/A
```

### Output of `brew doctor` and `brew config`

```shell
N/A
```

### Output of `brew tap`

```shell
N/A
```

### PR DESCRIPTION
**Pull request by ikunali**
Fixes #167997

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --cask --new <cask>` worked successfully.
- [ ] `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

---

### CODE REVIEW

**Comment by bevanjkay** [comment]
Can you please split this to an individual PR for each cask?

File: Casks/c/calibre.rb [hunk 1]
```diff
@@ -49,7 +49,7 @@
     end
   end
 
-  url "https://download.calibre-ebook.com/#{version}/calibre-#{version}.dmg"
+  url "https://github.com/kovidgoyal/calibre/releases/download/v#{version}/calibre-#{version}.dmg", verified: "github.com/kovidgoyal/calibre/"
```
Comment (cho-m) [inline Casks/c/calibre.rb:52]: Monterey and older `url` are broken with this as upstream deletes attachments from GitHub.

Also, we will probably see someone open another issue/PR to switch it back, which is what happened in past:
- https://github.com/Homebrew/homebrew-cask/issues/104814
- https://github.com/Homebrew/homebrew-cask/issues/10039

The fun history of the cask:
- 2021-05-07: GitHub to Homepage: https://github.com/Homebrew/homebrew-cask/commit/10bc7d8ef2754bbd50f764f821d77191c8a03c73
- 2020-05-02: Homepage to GitHub - https://github.com/Homebrew/homebrew-cask/commit/99a8dec21e85f3cba3b03e98312b52a1d85612da
- 2015-08-30: GitHub to Homepage https://github.com/Homebrew/homebrew-cask/commit/918a5a259545cdd33b4aed0a393092a3fd36c7e7
- 2015-03-08: Homepage to GitHub https://github.com/Homebrew/homebrew-cask/commit/35ec7255294cce29a2169dab2dcd967a51192426
- ...

Comment (krehel) [reply Casks/c/calibre.rb:52]: Yeah only the `burp` changes should be moved forward due to breakage of Calibre.

Comment (TG-KK) [reply Casks/c/calibre.rb:52]: Well, after reading all that, I should leave calibre as it is then, since it's going to be unreliable.

Thank you for letting me know about the history.

**Comment by TG-KK** [comment]
> Can you please split this to an individual PR for each cask?

Looks like GitHub releases for calibre are unreliable, so gonna have just burp suite as part of this PR now.

**Review by miccal — APPROVED** [review]

**Review by krehel — APPROVED** [review]
