### PR TITLE
Change Web-Sharing url

### LINKED ISSUE #11420: Cask fix request: web-sharing
Hello, 

Just noticed that the web-sharing cask was pointing to an invalid URL (the current one is a splash for VirtualHostX, so you get a "could not identify primary container' error):

The incorrect download is:
https://clickontyler.com/web-sharing/download/

The correct download should be: 
https://clickontyler.com/web-sharing/download/v1/

### PR DESCRIPTION
**Pull request by roddehugo**
Fix #11420

### CODE REVIEW

File: Casks/web-sharing.rb [hunk 1]
```diff
@@ -1,8 +1,8 @@
 cask :v1 => 'web-sharing' do
-  version :latest
+  version '1.0'
   sha256 :no_check
```
Comment (vitorgalvao) [inline Casks/web-sharing.rb]: `sha256` also needs to be updated. You can find what it is by running `shasum -a 256` on the downloaded file.

**Comment by roddehugo** [comment]
Shasum updated
