### PR TITLE
kafka-tool: update to 2.1 with new offset-explorer name and 'app' install

### LINKED ISSUE #101141: Kafka-tool not moved to /Applications folder
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

kafka-tool is installed at /usr/local/Caskroom/kafka-tool/2.0.8/Kafka\ Tool\ 2.app but not moved to Applications folder

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/kafka-tool.rb

### Command that failed

brew install --cask kafka-tools

### Output of command with `--verbose --debug`

```
➜  ~ brew install --cask kafka-tool --verbose --debug                        11
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading https://www.kafkatool.com/download2/kafkatool.dmg
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.0.5\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.2.3\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://www.kafkatool.com/download2/kafkatool.dmg
Already downloaded: /Users/javierddn/Library/Caches/Homebrew/downloads/bac14188c4e9124e3da5390ab69412660fa5c009a3f70e7c1f8b9d0aa1a4e81c--kafkatool.dmg
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/javierddn/Library/Caches/Homebrew/downloads/bac14188c4e9124e3da5390ab69412660fa5c009a3f70e7c1f8b9d0aa1a4e81c--kafkatool.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/javierddn/Library/Caches/Homebrew/downloads/bac14188c4e9124e3da5390ab69412660fa5c009a3f70e7c1f8b9d0aa1a4e81c--kafkatool.dmg
==> /Users/javierddn/Library/Caches/Homebrew/downloads/bac14188c4e9124e3da5390ab69412660fa5c009a3f70e7c1f8b9d0aa1a4e81c--kafkatool.dmg is quarantined
Warning: No checksum defined for cask 'kafka-tool', skipping verification.
hdiutil imageinfo -format /Users/javierddn/Library/Caches/Homebrew/downloads/bac14188c4e9124e3da5390ab69412660fa5c009a3f70e7c1f8b9d0aa1a4e81c--kafkatool.dmg
==> Installing Cask kafka-tool
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Dmg for /Users/javierddn/Library/Caches/Homebrew/downloads/bac14188c4e9124e3da5390ab69412660fa5c009a3f70e7c1f8b9d0aa1a4e81c--kafkatool.dmg
hdiutil attach -plist -nobrowse -readonly -mountrandom /private/tmp/d20210315-74527-mv7vdw /Users/javierddn/Library/Caches/Homebrew/downloads/bac14188c4e9124e3da5390ab69412660fa5c009a3f70e7c1f8b9d0aa1a4e81c--kafkatool.dmg
find . -print0
mkbom -s -i /private/tmp/20210315-74527-ca0wcx.list -- /private/tmp/20210315-74527-80nr7l.bom
ditto --bom /private/tmp/20210315-74527-80nr7l.bom -- /private/tmp/d20210315-74527-mv7vdw/dmg.jWZGPq /private/tmp/d20210315-74527-1n8n42m
diskutil eject /private/tmp/d20210315-74527-mv7vdw/dmg.jWZGPq
cp -pR /private/tmp/d20210315-74527-1n8n42m/Kafka\ Tool\ 2.app/. /usr/local/Caskroom/kafka-tool/2.0.8/Kafka\ Tool\ 2.app
chmod -Rf +w /private/tmp/d20210315-74527-1n8n42m
==> Verifying Gatekeeper status of /Users/javierddn/Library/Caches/Homebrew/downloads/bac14188c4e9124e3da5390ab69412660fa5c009a3f70e7c1f8b9d0aa1a4e81c--kafkatool.dmg
/usr/bin/xattr -p com.apple.quarantine /Users/javierddn/Library/Caches/Homebrew/downloads/bac14188c4e9124e3da5390ab69412660fa5c009a3f70e7c1f8b9d0aa1a4e81c--kafkatool.dmg
==> /Users/javierddn/Library/Caches/Homebrew/downloads/bac14188c4e9124e3da5390ab69412660fa5c009a3f70e7c1f8b9d0aa1a4e81c--kafkatool.dmg is quarantined
==> Propagating quarantine from /Users/javierddn/Library/Caches/Homebrew/downloads/bac14188c4e9124e3da5390ab69412660fa5c009a3f70e7c1f8b9d0aa1a4e81c--kafkatool.dmg to /usr/local/Caskroom/kafka-tool/2.0.8
/usr/bin/xattr -p com.apple.quarantine /Users/javierddn/Library/Caches/Homebrew/downloads/bac14188c4e9124e3da5390ab69412660fa5c009a3f70e7c1f8b9d0aa1a4e81c--kafkatool.dmg
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;604f59b2\;Homebrew\\x20Cask\;64DC24B2-E226-4566-8484-80E318033FFB
==> Creating metadata directory: /usr/local/Caskroom/kafka-tool/.metadata/2.0.8/20210315140828.194
==> Creating metadata subdirectory: /usr/local/Caskroom/kafka-tool/.metadata/2.0.8/20210315140828.194/Casks
==> Installing artifacts
==> 3 artifacts defined
#<SortedSet: {#<Cask::Artifact::Uninstall:0x00007fb0109e1f48 @cask=#<Cask::Cask:0x00007fb01129ad38 @token="kafka-tool", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/kafka-tool.rb>, @tap=#<Tap:0x00007fb011271c58 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fb01129ac98@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/kafka-tool.rb:1>, @default_config=#<Cask::Config:0x00007fb011292a70 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/kafka-tool>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/kafka-tool/.metadata>, @config=#<Cask::Config:0x00007fb0109d99d8 @explicit={}>, @dsl=#<Cask::DSL:0x00007fb0109d9550 @cask=#<Cask::Cask:0x00007fb01129ad38 ...>, @token="kafka-tool", @version="2.0.8", @sha256=:no_check, @url=#<URL:0x00007fb0109d8b28 @uri=#<URI::HTTPS https://www.kafkatool.com/download2/kafkatool.dmg>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:user_agent=>:default}, @from_block=false, @caller_location="/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/kafka-tool.rb:5:in `block in load'">, @appcast=#<Cask::DSL::Appcast:0x00007fb0109d86c8 @uri=#<URI::HTTPS https://www.kafkatool.com/download.html>, @parameters={}>, @name=["Kafka Tool"], @homepage="https://www.kafkatool.com/index.html", @artifacts=#<SortedSet: {...}>, @language_eval=nil>>, @directives={:delete=>"/Applications/Kafka Tool.app", :signal=>[]}>, #<Cask::Artifact::Installer:0x00007fb0109e2b00 @cask=#<Cask::Cask:0x00007fb01129ad38 @token="kafka-tool", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/kafka-tool.rb>, @tap=#<Tap:0x00007fb011271c58 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fb01129ac98@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/kafka-tool.rb:1>, @default_config=#<Cask::Config:0x00007fb011292a70 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/kafka-tool>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/kafka-tool/.metadata>, @config=#<Cask::Config:0x00007fb0109d99d8 @explicit={}>, @dsl=#<Cask::DSL:0x00007fb0109d9550 @cask=#<Cask::Cask:0x00007fb01129ad38 ...>, @token="kafka-tool", @version="2.0.8", @sha256=:no_check, @url=#<URL:0x00007fb0109d8b28 @uri=#<URI::HTTPS https://www.kafkatool.com/download2/kafkatool.dmg>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:user_agent=>:default}, @from_block=false, @caller_location="/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/kafka-tool.rb:5:in `block in load'">, @appcast=#<Cask::DSL::Appcast:0x00007fb0109d86c8 @uri=#<URI::HTTPS https://www.kafkatool.com/download.html>, @parameters={}>, @name=["Kafka Tool"], @homepage="https://www.kafkatool.com/index.html", @artifacts=#<SortedSet: {...}>, @language_eval=nil>>, @args={:must_succeed=>true, :sudo=>false, :args=>["-q"], :print_stdout=>true}, @path=#<Pathname:Kafka Tool 2.app/Contents/MacOS/JavaApplicationStub>>, #<Cask::Artifact::Zap:0x00007fb0109e14f8 @cask=#<Cask::Cask:0x00007fb01129ad38 @token="kafka-tool", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/kafka-tool.rb>, @tap=#<Tap:0x00007fb011271c58 @user="Homebrew", @repo="cask", @name="homebrew/cask", @full_name="Homebrew/homebrew-cask", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks>>, @block=#<Proc:0x00007fb01129ac98@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/kafka-tool.rb:1>, @default_config=#<Cask::Config:0x00007fb011292a70 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/kafka-tool>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/kafka-tool/.metadata>, @config=#<Cask::Config:0x00007fb0109d99d8 @explicit={}>, @dsl=#<Cask::DSL:0x00007fb0109d9550 @cask=#<Cask::Cask:0x00007fb01129ad38 ...>, @token="kafka-tool", @version="2.0.8", @sha256=:no_check, @url=#<URL:0x00007fb0109d8b28 @uri=#<URI::HTTPS https://www.kafkatool.com/download2/kafkatool.dmg>, @verified=nil, @using=nil, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=nil, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:user_agent=>:default}, @from_block=false, @caller_location="/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/kafka-tool.rb:5:in `block in load'">, @appcast=#<Cask::DSL::Appcast:0x00007fb0109d86c8 @uri=#<URI::HTTPS https://www.kafkatool.com/download.html>, @parameters={}>, @name=["Kafka Tool"], @homepage="https://www.kafkatool.com/index.html", @artifacts=#<SortedSet: {...}>, @language_eval=nil>>, @directives={:trash=>"~/.kafkatool2", :signal=>[]}>}>
==> Installing artifact of class Cask::Artifact::Installer
==> Running installer script 'Kafka Tool 2.app/Contents/MacOS/JavaApplicationStub'
/usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/kafka-tool/2.0.8/Kafka\ Tool\ 2.app/Contents/MacOS/JavaApplicationStub -q
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
🍺  kafka-tool was successfully installed!                                /15,6s
```

### Output of `brew doctor --verbose`

```
➜  ~ brew doctor --verbose                                                   11
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/warning-1.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tapioca-0.4.15/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/spoom-1.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thor-1.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-1.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unicode-display_width-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-ast-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-sorbet-1.8.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-0.5.6274/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-static-0.5.6274-universal-darwin-14/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-github-2.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-3.10.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-mocks-3.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-expectations-3.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-core-3.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-support-3.10.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/regexp_parser-2.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rdiscount-2.2.0.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/rdiscount-2.2.0.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/pry-0.14.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parlour-5.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-0.5.6274/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parser-3.0.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel_tests-3.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/parallel-1.20.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mustache-1.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/method_source-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrick-1.7.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/nokogiri-1.11.1-x86_64-darwin/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/racc-1.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/racc-1.5.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-persistent-4.0.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-3.3.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mime-types-data-3.2021.0212/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf_ext-0.0.7.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/unf_ext-0.0.7.7
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/diff-lcs-1.4.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/connection_pool-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/commander-4.5.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/highline-2.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/colorize-0.8.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/coderay-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/codecov-0.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-0.21.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov-html-0.12.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/byebug-11.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/byebug-11.1.3
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bootsnap-1.7.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/bootsnap-1.7.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/msgpack-1.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/x86_64-darwin-14/2.6.0-static/msgpack-1.4.2
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ast-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/minitest-5.14.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin20
/Library/Ruby/Site/2.6.0/universal-darwin20
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin20
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin20
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin20
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20
/usr/local/Homebrew/Library/Homebrew
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Homebrew Version
3.0.5
==> macOS
11.2.3
==> SIP
Enabled
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3855 casks)
/usr/bin/xattr
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc                   /4,0s
```

### Output of `brew tap`

```
➜  ~ brew tap                                                                11
homebrew/cask
homebrew/core                                                              /1,0s
```

### PR DESCRIPTION
**Pull request by cho-m**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Fixes #101141 

### Changes Summary
1. New name "Offset Explorer" according to homepage: https://www.kafkatool.com/
2. Version update from 2.0.9 -> 2.1
3. Switched appcast to livecheck
4. Cask doesn't seem to use installer script anymore. Manual install shows drag-and-drop, so switched to `app`
    offset-explorer-install
5. **NOTE**: Even with new name, the local data is stored inside `~/.kafkatool2` (at least in v2.1)

### Sample install
```console
❯ brew install kafka-tool
==> Downloading https://www.kafkatool.com/download2/offsetexplorer.dmg
######################################################################## 100.0%
Warning: No checksum defined for cask 'kafka-tool', skipping verification.
==> Installing Cask kafka-tool
==> Moving App 'Offset Explorer 2.app' to '/Applications/Offset Explorer 2.app'
🍺  kafka-tool was successfully installed!

❯ brew uninstall kafka-tool
==> Uninstalling Cask kafka-tool
==> Backing App 'Offset Explorer 2.app' up to '/usr/local/Caskroom/kafka-tool/2.1/Offset Explorer 2.app'
==> Removing App '/Applications/Offset Explorer 2.app'
==> Purging files for version 2.1 of Cask kafka-tool

❯ brew uninstall --zap --cask --force kafka-tool
==> Implied `brew uninstall --cask kafka-tool`
==> Dispatching zap stanza
==> Trashing files:
~/.kafkatool2
==> Removing all staged versions of Cask 'kafka-tool'
```

### Cask Checks
```console
❯ brew audit --cask kafka-tool
audit for kafka-tool: passed

❯ brew style --fix kafka-tool

1 file inspected, no offenses detected
```

### CODE REVIEW

File: Casks/kafka-tool.rb [hunk 1]
```diff
@@ -1,18 +1,20 @@
 cask "kafka-tool" do
```
Comment (reitermarkus) [inline Casks/kafka-tool.rb:1]: This should be renamed.

Comment (cho-m) [reply Casks/kafka-tool.rb:1]: Is there a way to help users who currently have "kafka-tool" installed upgrade to "offset-explorer" as I assume file/cask rename would be considered different apps?

Comment (reitermarkus) [reply Casks/kafka-tool.rb:1]: > is there an recommended rename process

There isn't since there is no proper support for renaming casks, as mentioned in the caveat for `google-drive`. The caveat is really more of a workaround.

cc @vitorgalvao

Comment (cho-m) [reply Casks/kafka-tool.rb:1]: Okay. For now, I added new `offset-explorer.rb` file.

Depending on decision, I can either delete `kafka-tool.rb` or copy similar workaround from `google-drive-file-stream`

Comment (vitorgalvao) [reply Casks/kafka-tool.rb:1]: That `caveat` workaround is nasty to make, I don’t recommend it. You can just delete `kafka-tool.rb`.

What we’re in dire need of the equivalent of `formula_renames.json` for casks.

Comment (cho-m) [reply Casks/kafka-tool.rb]: Okay. I have committed changes. I will add snippet of sample install into comments.

**Comment by cho-m** [comment]
```console
❯ brew audit --cask offset-explorer
audit for offset-explorer: passed

❯ brew style --fix offset-explorer

1 file inspected, no offenses detected

❯ brew audit --new-cask offset-explorer
audit for offset-explorer: passed

❯  brew install --cask offset-explorer
==> Downloading https://www.kafkatool.com/download2/offsetexplorer.dmg
######################################################################## 100.0%
Warning: No checksum defined for cask 'offset-explorer', skipping verification.
==> Installing Cask offset-explorer
==> Moving App 'Offset Explorer 2.app' to '/Applications/Offset Explorer 2.app'
🍺  offset-explorer was successfully installed!

❯ open /Applications/Offset\ Explorer\ 2.app

❯ fd -IH 'kafka.*tool|offset.*explore' ~ -E '.cache/vim' -E 'Library/Caches/Homebrew' -E 'Code'
/Users/cho-m/.kafkatool2

❯ brew uninstall --cask offset-explorer
==> Uninstalling Cask offset-explorer
==> Backing App 'Offset Explorer 2.app' up to '/opt/homebrew/Caskroom/offset-explorer/2.1/Offset Explorer 2.app'
==> Removing App '/Applications/Offset Explorer 2.app'
==> Purging files for version 2.1 of Cask offset-explorer

❯ fd -IH 'kafka*tool|offset*explore' ~ -E '.cache/vim' -E 'Library/Caches/Homebrew' -E 'Code'
/Users/cho-m/.kafkatool2

❯ brew uninstall --zap --force --cask offset-explorer
==> Implied `brew uninstall --cask offset-explorer`
==> Dispatching zap stanza
==> Trashing files:
~/.kafkatool2
==> Removing all staged versions of Cask 'offset-explorer'

❯ fd -IH 'kafka*tool|offset*explore' ~ -E '.cache/vim' -E 'Library/Caches/Homebrew' -E 'Code'
/Users/cho-m/.Trash/.kafkatool2
```

**Review by vitorgalvao — APPROVED** [review]
